# Generated by Django 4.1.1 on 2023-03-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('comopstion', models.TextField()),
                ('pradapp', models.TextField()),
                ('category', models.CharField(choices=[('CR', 'curd'), ('ML', 'milk'), ('Ls', 'lassi'), ('Ms', 'Milkshake'), ('PN', 'panner'), ('GN', 'Ghee'), ('Ch', 'cheese'), ('ice', 'icecream')], max_length=3)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
