# Generated by Django 4.1.1 on 2023-03-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comopstion',
            field=models.TextField(default=''),
        ),
    ]
