# Generated by Django 4.1.1 on 2023-05-27 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_product_comopstion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('Zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andaman & nichobar Island', 'Andaman & nichobar Island'), ('Arunachal pradesh', 'Arunachal pradesh'), ('Asam', 'Asam'), ('Andrha Pradesh', 'Andrha Pradesh'), ('Bihar', 'Bihar'), ('chatisgrah', 'chatisgrah'), ('Goa', 'Goa'), ('gurjarat', 'gujarat'), ('hariyana', 'hariyana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Maharshtra', 'Mahrastra'), ('utterpradesh', 'utterpradesh'), ('utrakhand', 'utrakhand')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
